package com.assignments.stockmarket.navigation

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val SIGN_UP = "sign_up"
    const val FORGOT_PASSWORD = "forgot_password"
    const val MPIN = "mpin"
    const val MPIN_VERIFY = "mpin_verify"
    const val MPIN_RESET = "mpin_reset"
    const val WELCOME = "welcome"
    const val OTP = "otp/{email}/{otp}?isResetMpin={isResetMpin}&isForgotPassword={isForgotPassword}"
    const val MPIN_FINGER_PRINT = "mpin_finger_print"
    const val RESET_PASSWORD = "reset_password/{identifier}"
    const val DASHBOARD = "dashboard"
    const val SEARCH = "search"
    const val FAndQ = "f_and_o"
    const val MUTUAL_FUNDS = "mutual_funds"
    const val UPI = "upi"
    const val LOANS = "loans"
    const val BUY_STOCK = "buy_stock/{stockId}"
    const val BUY_STOCK_NAME = "buy_stock_name/{stockName}"
    const val ALL_STOCKS = "all_stocks"
    const val EXPLORE = "explore"
    const val HOLDINGS = "holdings"
    const val POSITIONS = "positions"
    const val ORDERS = "orders"
    const val INVESTMENT_AMOUNT = "investment_amount"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val NOTIFICATIONS_SETTINGS = "notification_settings"
    const val SECURITY_AND_LOGIN = "security_and_login"
    const val CHANGE_PASSWORD = "change_password"
    const val ABOUT = "about"
    const val HELP_AND_SUPPORT = "help_and_support"
    const val FUNDS_AND_PAYMENTS = "funds_and_payments"
    const val REPORTS = "reports"
    const val ACTIVE_DEVICES = "active_devices"
    const val KYC = "kyc"
    const val REFER_AND_EARN = "refer_and_earn"


}